version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: sis-postgres
    environment:
      POSTGRES_DB: sis_db
      POSTGRES_USER: sis_user
      POSTGRES_PASSWORD: sis_password
     ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sis-network
  app:
    build: .
    container_name: sis-app
    depends_on:
      - db
    networks:
      - sis-network


volumes:
  pgdata:

networks:
  sis-network:

